name: CI/CD Pipeline

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx (for cross-platform builds and caching)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Build Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          tags: flask-fitness-app:latest
          load: true  # Loads image into Docker for next steps

      # Check all files in the Docker image
      - name: List files in Docker image
        run: docker run --rm flask-fitness-app:latest ls -R /app

      # Step 4: Run Pytest tests inside the built Docker image
      - name: Run Pytest in Docker container
        run: |
          docker run --rm flask-fitness-app:latest pytest unit_tests/ 
